"""User Modification

Revision ID: c41eb19aa115
Revises: 92587a869827
Create Date: 2024-09-10 21:46:24.910078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41eb19aa115'
down_revision: Union[str, None] = '92587a869827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_profile_img', table_name='users')
    op.drop_column('users', 'profile_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.VARCHAR(), nullable=True))
    op.create_index('ix_users_profile_img', 'users', ['profile_img'], unique=False)
    # ### end Alembic commands ###
